version: '3.7'
services:
    database:
        image: 'postgres:11-alpine'
        environment:
            POSTGRES_PASSWORD: main
            POSTGRES_USER: main
            POSTGRES_DB: db_shop_relationship
        ports:
            - '5433:5432'
        volumes:
            - ./var/postgres-data:/var/lib/postgresql
    rabbitmq:
        image: rabbitmq:3.7-management
        ports:
            - '5673:5672'
            - '15673:15672'
        volumes:
            - ./var/data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit:cached
    redis:
        image: redis:5-alpine
        ports:
            - "6380:6379"